name: Trigger BookCart Cypress tests
on: 
  workflow_dispatch
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository test
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run cy:run:bookcart
